include: package:effective_dart/analysis_options.1.2.0.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
  errors: 
    missing_required_param: error
    directives_ordering: error
