name: totally_not_chernobyl
description: This game is part of my Bachelor's Thesis.
version: 0.5.0+1
author: Honza Bittner <git@tenhobi.dev>
repository: https://github.com/tenhobi/totally-not-chernobyl
issue_tracker: https://github.com/tenhobi/totally-not-chernobyl/issues
homepage: https://github.com/tenhobi/totally-not-chernobyl

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  bloc: ^4.0.0
  cloud_firestore: ^0.13.5
  dartz: ^0.9.1
  easy_localization: ^2.2.1
  easy_localization_loader: ^0.0.2
  equatable: ^1.1.1
  firebase_auth: ^0.16.0
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  # get_it: ^4.0.1
  google_fonts: ^1.1.0
  google_sign_in: ^4.4.1
  json_serializable: ^3.3.0
  meta: ^1.1.8
  package_info: '>=0.4.0+17 <2.0.0'
  sensors: ^0.4.1+10 #
  shared_preferences: ^0.5.7
  freezed_annotation: ^0.7.1 # flutter pub run build_runner build
  url_launcher: ^5.4.7
  shake: ^0.1.0

dev_dependencies:
  build_runner: ^1.8.1
  effective_dart: ^1.2.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  freezed: ^0.10.6
  mockito: ^4.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/locale/

# flutter pub run flutter_launcher_icons:main
# https://github.com/fluttercommunity/flutter_launcher_icons#mag-attributes
flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon.png'

# flutter pub run flutter_native_splash:create
# https://github.com/henriquearthur/flutter_native_splash
flutter_native_splash:
  #  image: 'assets/images/splash.png'
  color: 'f9a825'
  fill: true
