name: Create Labels

on: [issues]

labeler:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run Labeler
      if: success()
      uses: crazy-max/ghaction-github-labeler@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        yaml_file: .github/labels.yml
        exclude: "['help*', '*issue']"
        skip_delete: false
        dry_run: false
