name: Build

on: [push]

env:
  flutter_channel: 'stable'
  flutter_version: '1.12.13+hotfix.9'

jobs:
  # Analyze and test each package.
  analyze-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.OS }}-flutter-cache-${{ env.flutter_version }}
          restore-keys: |
            ${{ runner.OS }}-flutter-cache-

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - name: Analyze and Test
        run: |
          ./tool/ci.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
  #
  # Build mobile apps.
  # build:
  #   runs-on: ${{ matrix.os }}
  #   needs: analyze-and-test
  ##
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #     fail-fast: false
  ##
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Cache Flutter
  #       id: cache-flutter
  #       uses: actions/cache@v1
  #       with:
  #         path: /opt/hostedtoolcache/flutter
  #         key: ${{ runner.os }}-flutter
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         channel: 'stable'
  #     - name: Build Android
  #       run: |
  #         ./tool/build.sh apk
  #     - name: Build iOS
  #       if: ${{ runner.os }} == 'macOS'
  #       run: |
  #         ./tool/build.sh ios
